[DEFAULT]
SCHEMA_GOOGLE_TRENDS_TEMP=google_trends_temp 
SCHEMA_GOOGLE_TRENDS=google_trends
SCHEMA_JOB_INFO=job_info
GOOGLE_TRENDS_DIR_DOWNLOADED_FILES=C:\Users\sersn\Documents\GitHub\google_trends_to_postgres\files\downloaded_files\google_trends
GOOGLE_TRENDS_DIR_PARSED_FILES=C:\Users\sersn\Documents\GitHub\google_trends_to_postgres\files\parsed_files\google_trends
GOOGLE_TRENDS_DIR_ARCHIVED_FILES=C:\Users\sersn\Documents\GitHub\google_trends_to_postgres\files\archived_files\google_trends
JOB_STATUS_STARTED = STARTED 
JOB_STATUS_ERROR = ERROR 
JOB_STATUS_FINISHED = FINISHED
[GOOGLE_TRENDS]
TYPE=API
API_KEY=8a3ad574ff081bbf85ccc0f31f2ba5738304cfc363bffd11c89e2e70b1a251a1
SEARCH_PARAMETER_LIST=vpn,antivirus,ad blocker,password manager
COUNTRY=US
DAYS_OVERLAP=180
DATA_TYPE=TIMESERIES
TIMEZONE=-120
OUTPUT_FILE_FORMAT=csv

[POSTGRESQL_CONN]
TYPE=POSTGRESQL
HOST_NAME=localhost
PORT_NUMBER=5432
USERNAME=robertas
PASSWORD=dbpassword123
DATABASE=postgres