[DEFAULT]
SCHEMA_GOOGLE_TRENDS_TEMP= 
SCHEMA_GOOGLE_TRENDS=
SCHEMA_JOB_INFO=
SCHEMA_DWH_DIMENSIONS=
GOOGLE_TRENDS_DIR_DOWNLOADED_FILES=
GOOGLE_TRENDS_DIR_PARSED_FILES=
GOOGLE_TRENDS_DIR_ARCHIVED_FILES=
[GOOGLE_TRENDS]
TYPE=
API_KEY=
SEARCH_PARAMETER_LIST=
COUNTRY=
DAYS_OVERLAP=
DATA_TYPE=
TIMEZONE=
OUTPUT_FILE_FORMAT=

[POSTGRESQL_CONN]
TYPE=POSTGRESQL
HOST_NAME=
PORT_NUMBER=
USERNAME=
PASSWORD=
DATABASE=